version: '3'
services:
  dbt-de-zoomcamp:
    build:
      context: .
      target: dbt-bigquery
    working_dir: /usr/app/dbt/taxi_rides_ny
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ~/.google/credentials/google_credentials.json:/.google/credentials/google_credentials.json
    ports:
      - "8080:8080"
    network_mode: host